Neos:
  Neos:
    eventLog:
      enabled: true

    modules:
      management:
        submodules:
          history:
            controller: \Shel\Neos\History\Controller\HistoryController
            privilegeTarget: 'Shel.Neos.History:BackendModule'
            additionalResources:
              styleSheets:
                'Shel.Neos.History': 'resource://Shel.Neos.History/Public/Styles/Module.css'
              javaScripts:
                'Shel.Neos.History': 'resource://Shel.Neos.History/Public/JavaScript/App.js'

    userInterface:
      translation:
        autoInclude:
          'Shel.Neos.History':
            - 'Main'
